package resolvers

var help string = `placeholder help documentation
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et netus et malesuada fames ac. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Sed egestas egestas fringilla phasellus. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Orci ac auctor augue mauris augue neque gravida in. Lectus sit amet est placerat in egestas erat imperdiet sed. Eget dolor morbi non arcu risus quis varius quam. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Aliquam faucibus purus in massa tempor nec. Orci dapibus ultrices in iaculis nunc sed augue. Et malesuada fames ac turpis egestas integer. Tellus pellentesque eu tincidunt tortor aliquam nulla.

Sed felis eget velit aliquet sagittis id. Massa id neque aliquam vestibulum morbi. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Mauris pharetra et ultrices neque ornare. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Purus sit amet luctus venenatis lectus. Nulla facilisi etiam dignissim diam quis enim lobortis. Mattis ullamcorper velit sed ullamcorper. At tellus at urna condimentum mattis pellentesque. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Suspendisse sed nisi lacus sed viverra tellus in hac.

Aliquam id diam maecenas ultricies mi eget mauris pharetra. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Tincidunt lobortis feugiat vivamus at augue eget. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Auctor elit sed vulputate mi. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Lobortis feugiat vivamus at augue. Varius quam quisque id diam vel quam elementum pulvinar etiam. Id donec ultrices tincidunt arcu non sodales. Consequat ac felis donec et. Elit pellentesque habitant morbi tristique senectus et netus.

Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing elit pellentesque habitant morbi tristique senectus et. Metus aliquam eleifend mi in nulla posuere. In iaculis nunc sed augue lacus viverra vitae congue. Purus in mollis nunc sed id semper risus. Augue neque gravida in fermentum et. Vitae purus faucibus ornare suspendisse sed. Eu feugiat pretium nibh ipsum consequat. Urna neque viverra justo nec ultrices dui. Vulputate odio ut enim blandit volutpat maecenas volutpat. Placerat in egestas erat imperdiet. Pharetra diam sit amet nisl. Cursus mattis molestie a iaculis at. Malesuada fames ac turpis egestas. Suspendisse faucibus interdum posuere lorem ipsum dolor. Risus nullam eget felis eget nunc lobortis mattis aliquam faucibus.

Vel orci porta non pulvinar neque. Aenean et tortor at risus viverra. Morbi quis commodo odio aenean sed adipiscing diam donec. Interdum consectetur libero id faucibus nisl tincidunt eget. Turpis tincidunt id aliquet risus feugiat. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Viverra vitae congue eu consequat ac. Ut porttitor leo a diam sollicitudin. Est pellentesque elit ullamcorper dignissim cras. Massa tincidunt nunc pulvinar sapien et. Ut morbi tincidunt augue interdum velit. Sit amet tellus cras adipiscing. Sed cras ornare arcu dui vivamus arcu felis bibendum ut.

Adipiscing enim eu turpis egestas pretium aenean pharetra. Egestas dui id ornare arcu. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Turpis cursus in hac habitasse. Fermentum posuere urna nec tincidunt praesent semper. Eget mi proin sed libero enim sed faucibus turpis. Fames ac turpis egestas integer. Platea dictumst quisque sagittis purus sit amet. Aliquet nec ullamcorper sit amet risus nullam eget. Eu consequat ac felis donec et. Nec feugiat nisl pretium fusce. Ornare arcu odio ut sem. Eu tincidunt tortor aliquam nulla. Dolor morbi non arcu risus. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Leo vel fringilla est ullamcorper eget nulla facilisi.

Elementum integer enim neque volutpat ac tincidunt. Integer quis auctor elit sed vulputate mi. Diam vulputate ut pharetra sit amet. Enim ut sem viverra aliquet eget sit amet. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Et leo duis ut diam quam nulla. Leo duis ut diam quam. Nunc sed blandit libero volutpat sed cras. Fringilla est ullamcorper eget nulla facilisi. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Mollis aliquam ut porttitor leo a diam sollicitudin.

Sit amet purus gravida quis blandit. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Dignissim enim sit amet venenatis. Consequat interdum varius sit amet mattis. Elementum nibh tellus molestie nunc non blandit massa. Id ornare arcu odio ut sem nulla. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Senectus et netus et malesuada fames. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Egestas dui id ornare arcu odio ut. At erat pellentesque adipiscing commodo elit at imperdiet dui. Morbi non arcu risus quis varius quam quisque id. Sit amet dictum sit amet justo donec enim. Odio morbi quis commodo odio aenean sed adipiscing diam.

Erat pellentesque adipiscing commodo elit at imperdiet dui. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Habitant morbi tristique senectus et netus. Sollicitudin nibh sit amet commodo nulla. Et ligula ullamcorper malesuada proin libero nunc consequat. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Vitae turpis massa sed elementum tempus egestas. Penatibus et magnis dis parturient montes nascetur. Eget dolor morbi non arcu risus quis varius quam. Vulputate dignissim suspendisse in est ante in nibh. Pulvinar pellentesque habitant morbi tristique senectus et. Nulla facilisi etiam dignissim diam. Eleifend mi in nulla posuere sollicitudin aliquam. Quis risus sed vulputate odio. Non blandit massa enim nec dui nunc mattis. Purus non enim praesent elementum facilisis leo vel. Morbi tristique senectus et netus et malesuada fames ac turpis.

Egestas egestas fringilla phasellus faucibus. Sed sed risus pretium quam vulputate dignissim. Sem viverra aliquet eget sit amet tellus. Viverra nam libero justo laoreet. Sociis natoque penatibus et magnis dis parturient montes. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Orci porta non pulvinar neque laoreet. Posuere ac ut consequat semper viverra nam libero justo. Blandit libero volutpat sed cras. Tellus at urna condimentum mattis. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Quis ipsum suspendisse ultrices gravida dictum. Lectus proin nibh nisl condimentum id venenatis. Lacus vel facilisis volutpat est velit egestas dui. Dictumst quisque sagittis purus sit. Amet porttitor eget dolor morbi non arcu risus. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Justo donec enim diam vulputate ut.
`
